[target.aarch64-linux-android]
linker = "/home/osama/Android/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
ar = "/home/osama/Android/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
rustflags = ["-L/home/osama/gmp-android/lib"]